# Generated by Django 4.0.5 on 2022-06-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
